<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="4.18.1" />
      <PackageReference Include="QuestPDF" Version="2026.9.1" />
      <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.20" />
    </ItemGroup>

</Project>
